
services:
  backend:
    build: ./ai
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

